# Generated by Django 4.2.3 on 2023-07-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
